### PR TITLE
added new learner

### PR DESCRIPTION
**Pull request by MasSica**
Just using the playground to get acquainted with the Git procedures of Kubernetes. 

As mentioned in the readme, I have modified the remote repository and added my name in the list of participants.

This pull request is also useful for me in order to get  CLA agreement.

### CODE REVIEW

**Comment by shu-mutou** [comment]
Hello @MasSica  !
Welcome to k8s community!!
Please add the `<your github account>.md` file to the `learners/` directory instead of adding your github account to the `LEARNERS` file, to avoid conflicting PRs. Also, please remove `.idea` directory from your commit.
Thanks!

**Comment by MasSica** [comment]
Hi @shu-mutou !

Thank you for taking the time to review my pull request!

Is it all good now?

**Comment by shu-mutou** [comment]
Also, please remove `.idea` directory. Thanks!

**Comment by MasSica** [comment]
Hi @shu-mutou,

Could you please advise on how to do that ? I have tried a few things from Google (delete commit, remove directory), but I am not sure on how to proceed... 

Thank you

**Comment by shu-mutou** [comment]
@MasSica 

Please run followings:
* Simply remove `.idea` directory
* Do `git commit` and `git push origin master`

**Comment by MasSica** [comment]
@shu-mutou 

Done! Anything else to do ?

**Comment by shu-mutou** [comment]
/lgtm
/approve
Perfect!! Welcome to k8s community! :tada:

**Comment by shu-mutou** [comment]
Sorry for late response... :bow:

**Pull request merged**
