### PR TITLE
Move holding date to timetable in cndo-2021

### PR DESCRIPTION
**Pull request by atoato88**
This PR moves date description of training to timetable section.
We has created timetable section recently, so it's appropriate to collect in that section about datetime.

### CODE REVIEW

**Comment by atoato88** [comment]
/assign @YuikoTakada
Could you review this?

**Comment by shu-mutou** [comment]
/hold
Wait for @YuikoTakada being member of kubernetes-sigs.

**Comment by YuikoTakada** [comment]
Thank you for your PR.
/lgtm

**Pull request merged**
