### PR TITLE
My first PR added a md file in India folder

### PR DESCRIPTION
**Pull request by varshneydevansh**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by nikhita — COMMENTED** [review]
Please remove the `.vs` directory. Lgtm otherwise.

**Comment by nikhita** [comment]
@varshneydevansh the file `.vs/slnx.sqlite` still exists in this PR

**Comment by varshneydevansh** [comment]
I did try to remove the directory, but wasn't able to do so. Now, did it from the GitHub spaces.

image

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
