### PR TITLE
This is my first commit to Kubernetes Repository

### PR DESCRIPTION
**Pull request by Hemant-Sadana**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
Learning Purpose

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:
This PR is for learning purpose

**Does this PR introduce a user-facing change?**:
No

### CODE REVIEW

**Comment by palnabarun** [comment]
Hi @Hemant-Sadana 👋🏽, can you please rename the file you are adding to your <github username>.md?

**Comment by Hemant-Sadana** [comment]
> Hi @Hemant-Sadana 👋🏽, can you please rename the file you are adding to your .md?

Done

**Comment by palnabarun** [comment]
Yay! thanks!

/lgtm
/approve
/pony party

**Comment by RinkiyaKeDad** [comment]
/hold 
Hey @Hemant-Sadana! You've accidentally committed some MacOS specific files, could you please remove those? :)

**Pull request closed without merging**
