### PR TITLE
Added my first commit for practice and also removed someone's case-insentive commit

### PR DESCRIPTION
**Pull request by Anutrix**
**What type of PR is this?**
/kind cleanup
/kind documentation

**What this PR does / why we need it**:
Just a practice commit.

It also removes a @slayer321's commit 460e741e363ece80baf7278c2c8f44be52162ffc because on case-insensitive volumes like on Windows and Linux it shows this warning:
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'india/kcd-blr-2021/workdir/Sachin.md'
  'india/kcd-blr-2021/workdir/sachin.md'
```
when the repo is cloned and stays as
```
git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   india/kcd-blr-2021/workdir/Sachin.md
```
on git status.

This causes beginners and new contributors confusion.

**Which issue(s) this PR fixes**:
No issue ticket created for this.

**Does this PR introduce a user-facing change?**:
No

### CODE REVIEW

**Comment by palnabarun** [comment]
Hey Numan 👋🏽, thanks for cleaning the case-insensitive file.

Can you please rename the file to the person's GitHub username instead of removing it altogether?

**Comment by Anutrix** [comment]
> Hey Numan 👋🏽, thanks for cleaning the case-insensitive file.
> 
> Can you please rename the file to the person's GitHub username instead of removing it altogether?

Done. I made the changes.
I was thinking of merging the contents but renaming seems better. Thanks.

**Comment by palnabarun** [comment]
Thanks! Merging wouldn't have worked here as both the files had been created by two different users. :)

/lgtm
/approve

**Comment by Anutrix** [comment]
> Thanks! Merging wouldn't have worked here as both the files had been created by two different users. :)
> 
> /lgtm
> /approve

Thx for the approval.

My bad for considering merging content. I thought both were from same user.

**Comment by palnabarun** [comment]
No worries. :)

It's a bit non-trivial to find that.

**Pull request merged**
