### PR TITLE
Add woof.md (k8s blr workshop )

### PR DESCRIPTION
**Pull request by abhishekmishragithub**
Signed-off-by: Abhishek Mishra <geekabhi@outlook.com>
 A test PR 🐶

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

/meow

**Comment by palnabarun** [comment]
Hi 👋🏽, thank you for your pull request! 🎉 

Can you please send me an email at `404@naba.run`? We need your email ID for sending the swag code.

We look forward to seeing you in the community! 🙂

**Comment by abhishekmishragithub** [comment]
> Hi 👋🏽, thank you for your pull request! 🎉
> 
> Can you please send me an email at `404@naba.run`? We need your email ID for sending the swag code.
> 
> We look forward to seeing you in the community! 🙂

Yes @palnabarun, sure. 
Thanks 🙂

**Pull request merged**
