### PR TITLE
add shnmorimoto.md for ossj 2021 upstream training

### PR DESCRIPTION
**Pull request by shnmorimoto**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
training PR for ossj 2021 upstream training

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig node

### CODE REVIEW

**Comment by YuikoTakada** [comment]
Thank you for your PR!
/lgtm

**Comment by s-kawamura-w664** [comment]
Perfect!!
/shrug

**Pull request merged**
