### PR TITLE
added eveything-is-awesome.txt

### PR DESCRIPTION
**Pull request by chrisjsimpson**
:smile: TODO Fix spelling mistake!

### CODE REVIEW

**Comment by tpepper** [comment]
It looks like you either haven't signed the CLA, or your git config doesn't have an email that matches:
try this https://github.com/kubernetes-sigs/contributor-playground/blob/master/exercises/cla-vs-git-author.md

**Comment by tpepper** [comment]
Fun example change!  Thanks for submitting.  You need to fix the CLA issue, but otherwise...

/lgtm

**Comment by chrisjsimpson** [comment]
CLA signed

**Comment by chrisjsimpson** [comment]
Now cla is signed check :thinking:

**Comment by tpepper** [comment]
/lgtm
/approve

Thank you for coming to the workshop!  We hope you found it valuable and look forward to seeing you active in our Kubernetes community!

**Pull request merged**
