### PR TITLE
Move merged files placed at top folder in CNDW2024

### PR DESCRIPTION
**Pull request by atoato88**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR moves files which placed on the top of CNDW training folder.
In this training, merged files should place at `cndw-2024/workdir`. 
That's why this PR was created.

**Which issue(s) this PR fixes**:
NONE

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
NONE

### CODE REVIEW

**Comment by shu-mutou** [comment]
please move one more file nag.md

**Comment by atoato88** [comment]
done.

@shu-mutou 
PTAL.

**Comment by shu-mutou** [comment]
/lgtm
/approve
nice catch! thanks!!

**Pull request merged**
