### PR TITLE
add kmatsumoto.md

### PR DESCRIPTION
**Pull request by keima9933**
**What type of PR is this?**

> /kind documentation

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by mumoshu** [comment]
@keima9933 Perhaps you're missing your e-mail in your first commit?

image

**Comment by keima9933** [comment]
@ mumoshu
Thanks! I reflected your advice.

**Comment by atoato88** [comment]
/lgtm
/approve

Thank you :tada:

**Pull request merged**
