### PR TITLE
Fix typo in exercises/README.md

### PR DESCRIPTION
**Pull request by miles-**
Fixes https://github.com/kubernetes-sigs/contributor-playground/issues/129

@PaulineLc @magaldima @VaibhavPage PTAL

### CODE REVIEW

**Comment by idealhack** [comment]
lemme try this again after #159

/lgtm

**Comment by miles-** [comment]
@idealhack I think it'll only work for people in the main `OWNERS` file since the change I made doesn't have an OWNERS file.

**Comment by idealhack** [comment]
@miles- aha, that's why!

**Comment by grodrigues3** [comment]
Looks like this is a dupe of https://github.com/kubernetes-sigs/contributor-playground/pull/158

**Pull request closed without merging**
