### PR TITLE
kcdblr: Update pavanraga workdir

### PR DESCRIPTION
**Pull request by PavanRaga**
**What type of PR is this?**
 /kind documentation

**What this PR does / why we need it**:
Update pavanraga's workdir snapshot
**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:
None
**Does this PR introduce a user-facing change?**:
None

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
None

### CODE REVIEW

**Comment by RinkiyaKeDad** [comment]
/lgtm cancel
Please sign the CLA first :)

**Comment by nikhita** [comment]
@PavanRaga Congratulations on successfully getting your PR merged to kubernetes! :tada: 

Can you please let us know your email ID for us to email you the coupon code for swags?

You can either post your email as a comment here (on this PR) or DM me on the [Kubernetes](https://slack.k8s.io/) slack (I'm `@nikhita` on slack).

**Comment by PavanRaga** [comment]
hey, @nikhita thanks. 
My id is pavan.raga98@gmail.com

**Pull request merged**
