### PR TITLE
Add ziyi.md for cndt-2021 demo

### PR DESCRIPTION
**Pull request by ziyi-xie**
**What type of PR is this?**
 /kind documentation

**What this PR does / why we need it**:
Add ziyi.md for cndt-2021 demo
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig testing

### CODE REVIEW

**Comment by YuikoTakada** [comment]
xie-san, thank you for your PR! 
/lgtm

**Comment by shu-mutou** [comment]
/approve
Perfect!! Welcome to the kubernetes community!! 🎉

**Pull request merged**
