### PR TITLE
PR-KCDBLR'21

### PR DESCRIPTION
**Pull request by Edge2Ops**
What type of PR is this? **
> /kind documentation

What this PR does / why we need it:
None

Which issue(s) this PR fixes:
None

Special notes for your reviewer:
Thanks to all the organizers :)

Does this PR introduce a user-facing change?
None

giphy

### CODE REVIEW

**Comment by Edge2Ops** [comment]
Thanks @RinkiyaKeDad :)

**Comment by palnabarun** [comment]
Hi 👋🏽, can you please let us know your email ID for us to email you the coupon code for swags?

**Comment by Edge2Ops** [comment]
Hi there 😊


Thanks for reaching out, Please feel free to send it over : ***@***.******@***.***> ; Looking forward for the recording :D






Thanks & Regards
Yusuf

**Comment by MadhavJivrajani** [comment]
@Edge2Ops you'll have to comment from the PR page because of email masking

**Comment by Edge2Ops** [comment]
Thanks for highlighting this Madhav, I’ve updated the comment 😊

**Comment by Edge2Ops** [comment]
> @Edge2Ops you'll have to comment from the PR page because of email masking

@MadhavJivrajani feel free to send it over yufi.alam@outlook.com
/honk

**Pull request merged**
