### PR TITLE
add s-arai.md for ood-2022

### PR DESCRIPTION
**Pull request by yanaraha**
What type of PR is this?
/kind documentation

What this PR does / why we need it:

This PR add s-arai.md file for odd-2022 demo.

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

NONE
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

/sig node

### CODE REVIEW

**Comment by ziyi-xie** [comment]
Thank you for the PR!
Please check the following link and get CLA signed~
https://github.com/kubernetes-sigs/contributor-playground/blob/master/japan/assets/attendee-prerequisites.md#%E3%82%B5%E3%82%A4%E3%83%B3%E3%82%A2%E3%83%83%E3%83%97%E4%BD%9C%E6%A5%AD

**Comment by atoato88** [comment]
EasyCLA bot said "MISSING ID ON COMMIT".
Could you check the ID on your commit?

**Comment by atoato88** [comment]
Please check this document too.

https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user

**Comment by shu-mutou** [comment]
/close
I closed the PR, but feel free to type the `/reopen` command if you want to reopen it.

**Pull request closed without merging**
