### PR TITLE
commit doc file

### PR DESCRIPTION
**Pull request by VenkatesanSathish**
**What type of PR is this?**
 /kind documentation
Add sathish-macro.md for ood-2022 demo

**What this PR does / why we need it**:
Fixes #

### CODE REVIEW

**Comment by atoato88** [comment]
Please sign the CLA first.

**Comment by atoato88** [comment]
Thank you for creating this PR.
The content is LGTM.

**Comment by shu-mutou** [comment]
Please see this documents for signing CLA.
https://github.com/kubernetes-sigs/contributor-playground/blob/master/japan/assets/attendee-prerequisites.md#%E3%82%B5%E3%82%A4%E3%83%B3%E3%82%A2%E3%83%83%E3%83%97%E4%BD%9C%E6%A5%AD

**Comment by shu-mutou** [comment]
/lgtm
Thanks! Welcome to k8s community! :tada:

**Pull request merged**
