### PR TITLE
Adding new markdown file

### PR DESCRIPTION
**Pull request by VikasManohar**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
None
**Which issue(s) this PR fixes**:
None

Fixes #

**Special notes for your reviewer**:
Thank you for the workshop
**Does this PR introduce a user-facing change?**:

```release-note
No
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by VikasManohar** [comment]
check CLA

**Comment by RinkiyaKeDad** [comment]
Hi 👋🏽, can you please let us know your email ID for us to email you the coupon code for swags?

**Comment by VikasManohar** [comment]
> Hi 👋🏽, can you please let us know your email ID for us to email you the coupon code for swags?

Hi, vikasmanohar.1995@gmail.com 
:)

**Comment by RinkiyaKeDad** [comment]
Sent :)

**Pull request merged**
