### PR TITLE
add toricls.md

### PR DESCRIPTION
**Pull request by toricls**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This is a PR created at the Kubernetes upstream training in CNDT 2021.

**Which issue(s) this PR fixes**:

NONE

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig test-never-exists

### CODE REVIEW

**Comment by toricls** [comment]
> @toricls: The label(s) `language/ja` cannot be applied, because the repository doesn't have them.

Sure

**Comment by toricls** [comment]
Thanks @atoato88 for the ultra fast review!

**Comment by atoato88** [comment]
yeah, no problem :smile:

**Comment by toricls** [comment]
@inductor /say-funny-thing

**Comment by inductor** [comment]
@toricls Futon was blown away

**Pull request merged**
