### PR TITLE
Add sshambar.md to remote/learners folder

### PR DESCRIPTION
**Pull request by sshambar**
Try to sign the CLA

### CODE REVIEW

**Comment by sshambar** [comment]
@ziyi-xie - Hi, I completed the EasyCLA process 3 times (in different browsers) - received the email confirmation for all 3, but doesn't appear to be tagging here.  Does this process usually take more than 4 hours?  Thanks...

**Comment by ziyi-xie** [comment]
Looks like the email address you used to commit is devel@shambarger.net, is this the same email address you used when you applied for your Github account?

**Comment by ziyi-xie** [comment]
Thanks! Looks like you passed the CLA test! It does get confusing sometimes...

I noticed that your title and commit message is "Try to sign the CLA", I think it might be even more perfect if you add more details (e.g. add sshambar.md to remote/learners folder).
Also this is a practice repository, so please follow the PR template if possible :)

**Comment by ziyi-xie** [comment]
Thanks! Welcome to the K8s community!
/lgtm
/approve

/meow

**Pull request merged**
