### PR TITLE
Add naotospace.md for exercise

### PR DESCRIPTION
**Pull request by naotospace**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by shu-mutou** [comment]
/honk
Thanks!

**Comment by s-ito-ts** [comment]
/approve

Thank you for PR!

**Pull request merged**
