### PR TITLE
Added myself as a learner to sign CLA

### PR DESCRIPTION
**Pull request by troll-os**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by shu-mutou** [comment]
You can sign CLA by clicking `NOT COVERED` button.
By_AaGTyye

**Comment by troll-os** [comment]
Hello @shu-mutou 

I was coordinating with my company as we're proceeding to enroll as a new organization. 
We're currently in a waiting state "Your organization is not yet enrolled in EasyCLA. For security, please click here to open a support ticket."

I'll file a ticket if we don't have updates in the next few days 

Thanks for the heads up !

**Comment by shu-mutou** [comment]
> I was coordinating with my company as we're proceeding to enroll as a new organization.

That's great! It will take time, so there's no need to rush!

**Comment by troll-os** [comment]
Hello @shu-mutou 

Everything cleared on my side :) 

Best regards

**Comment by shu-mutou** [comment]
/lgtm
/approve
Welcome to K8s community 🎉

**Comment by shu-mutou** [comment]
Perfect!! Enjoy your contribution!!
/meow

**Pull request merged**
