### PR TITLE
HelloWorld from jin

### PR DESCRIPTION
**Pull request by jmz331**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes `NONE`

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

`NONE`

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by jmz331** [comment]
Signed the CLA

**Comment by mumoshu** [comment]
@jmz331 Which email did you use to sign CLA? You need to match the email used to sign CLA and make git commit. Perhaps that's the issue.

I see you have `chinajmz@gmail.com` in your commit so you'll need to sign CLA with it:

```
commit 09b233301a8040dc06d34d43331dd3b7d9423080 (HEAD -> feature/test-change-jin)
Author: ZhanYi PC <chinajmz@gmail.com>
Date:   Mon Jul 22 17:13:23 2019 +0900

    test code
```

**Pull request closed without merging**
