### PR TITLE
My first PR

### PR DESCRIPTION
**Pull request by mpmaia**
First test contribution created during KCD Brazil

/kind cleanup

**Special notes for your reviewer**:

None

**Does this PR introduce a user-facing change?**:

No

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

None

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/approve
Welcome to k8s community!

**Comment by rikatz** [comment]
/lgtm
Obrigado e bem vindo!

**Pull request merged**
