### PR TITLE
Update OOD2019 upstream training prerequisites instruction

### PR DESCRIPTION
**Pull request by amotoki**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Update and reorganize the instruction to prepare GitHub account and CNCF CLA.
It clarifies the instruction and the notice on the email address used.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by atoato88** [comment]
Can you add `Does this PR introduce a user-facing change?:` section to this PR description?
It is mandatory for PR description.

e.g.
```
NONE
```

**Comment by amotoki** [comment]
> Can you add `Does this PR introduce a user-facing change?:` section to this PR description?
> It is mandatory for PR description.
> 
> e.g.
> 
> ```
> NONE
> ```

**Comment by amotoki** [comment]
> Can you add `Does this PR introduce a user-facing change?:` section to this PR description?
> It is mandatory for PR description.
> 
> e.g.
> 
> ```
> NONE
> ```

Done. I updated the PR description.

**Comment by amotoki** [comment]
The release note section in the PR description is now updated.

**Comment by shu-mutou** [comment]
/lgtm
/approve
Greate update! Thanks!!

**Comment by atoato88** [comment]
Thank you for update.

**Pull request merged**
