### PR TITLE
Add minamiii.md

### PR DESCRIPTION
**Pull request by TatsukiMinami**
#### What type of PR is this? 
/kind documentation

#### What this PR does / why we need it:
To complete kft-2020 workshop.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?:

```
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```
```

### CODE REVIEW

**Comment by atoato88** [comment]
Like [this PR](https://github.com/kubernetes-sigs/contributor-playground/pull/505), Could you write description in markdown format?

**Comment by shu-mutou** [comment]
/lgtm
Perfect!!

**Pull request merged**
