### PR TITLE
Add katsuharu.md for ood-2022 hands on

### PR DESCRIPTION
**Pull request by katsuharu**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig node

### CODE REVIEW

**Comment by ziyi-xie** [comment]
Thanks! Welcome to the community~
/lgtm

**Comment by katsuharu** [comment]
@ziyi-xie 
Thank you very much for your review!

**Comment by oomichi** [comment]
Thanks for your contribution!

/approve

**Comment by katsuharu** [comment]
@oomichi thank you for your review!

**Pull request merged**
