### PR TITLE
add mosuke5.md for demo

### PR DESCRIPTION
**Pull request by mosuke5**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This is my first PR in CNDT2021

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
- [Other doc]: https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/
```

/sig testing

### CODE REVIEW

**Comment by mosuke5** [comment]
some words /trick-or-treat

**Comment by mosuke5** [comment]
other word
/trick-or-treat

**Comment by shu-mutou** [comment]
/lgtm
/approve
Perfect! Welcome to the kubernetes community!! 🎉

**Comment by atoato88** [comment]
LGTM!!

**Comment by YuikoTakada** [comment]
Thank you for your PR!

**Pull request merged**
