### PR TITLE
add workshop impression

### PR DESCRIPTION
**Pull request by kimullaa**
**What type of PR is this?**
/kind documentation

> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This adds kimullaa.md for kft-2020.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by s-ito-ts** [comment]
/lgtm
/approve

Thank you for PR!

**Comment by kimullaa** [comment]
/joke
--

**Pull request merged**
