### PR TITLE
Updated OWNERS files to use go.k8s.io for pointing to docs

### PR DESCRIPTION
**Pull request by rlenferink**
As the title says

### CODE REVIEW

**Comment by rlenferink** [comment]
Removed the beijing/OWNERS file because approvers/reviewers need to be part of k8s-sigs

**Comment by rlenferink** [comment]
ping @jberkus

**Comment by guineveresaenger** [comment]
@rlenferink on this repository, you don NOT need membership to be in an OWNERS file, as practice with labels and permissions is the point of this repo.
Regardless, the Beijing workshop is done, so it's ok to leave it deleted in my book.

/lgtm
/approve

**Comment by rlenferink** [comment]
> @rlenferink on this repository, you don NOT need membership to be in an OWNERS file, as practice with labels and permissions is the point of this repo.
> Regardless, the Beijing workshop is done, so it's ok to leave it deleted in my book.
> 
> /lgtm
> /approve

@guineveresaenger Thanks for confirming, that's what I thought as well, but then why is the `invalid-owners-file` plugin [adding labels](https://github.com/kubernetes-sigs/contributor-playground/pull/234#issuecomment-487130099) to this PR (the label is still present, so prow won't merge this PR) ?

**Comment by nikhita** [comment]
> why is the invalid-owners-file plugin adding labels to this PR (the label is still present, so prow won't merge this PR) ?

Manually removed the label since the label has been disabled for all orgs. That's a bug :) thanks for catching that!

**Pull request merged**
