### PR TITLE
Added rtnpro.md.

### PR DESCRIPTION
**Pull request by rtnpro**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Hands on contributor playground

**Which issue(s) this PR fixes**:
NONE

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

NO

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by surajssd** [comment]
\0/ RTN 

/joke

**Comment by palnabarun** [comment]
Hi 👋🏽, thank you for your pull request! 🎉 

Can you please send me an email at `404@naba.run`? We need your email ID for sending the swag code.

We look forward to seeing you in the community! 🙂

**Comment by rtnpro** [comment]
My email is

rtnpro AT gmail DOT com

**Pull request merged**
