### PR TITLE
Changed date to May

### PR DESCRIPTION
**Pull request by markpudd**
Changed the date in title to add the month.

### CODE REVIEW

**Comment by markpudd** [comment]
Signed CLA

**Comment by tpepper** [comment]
It looks like you either haven't signed the CLA, or your git config doesn't have an email that matches:
try this https://github.com/kubernetes-sigs/contributor-playground/blob/master/exercises/cla-vs-git-author.md

**Comment by tpepper** [comment]
/close

Thank you for coming to the workshop!  We hope you found it valuable and look forward to seeing you active in our Kubernetes community!

@markpudd if you need some help on CLA signing feel free to ping me or the others in the #sig-contribex

**Pull request closed without merging**
