### PR TITLE
PR-practice

### PR DESCRIPTION
**Pull request by cchengleo**
Table 5 practice

### CODE REVIEW

**Comment by tpepper** [comment]
As Guin just mentioned you may have a mismatch in your git config versus when you signed the CLA: https://github.com/kubernetes-sigs/contributor-playground/blob/master/exercises/cla-vs-git-author.md

**Comment by cchengleo** [comment]
> As Guin just mentioned you may have a mismatch in your git config versus when you signed the CLA: https://github.com/kubernetes-sigs/contributor-playground/blob/master/exercises/cla-vs-git-author.md

I followed the instruction, but still not working. Do I have to abondon this PR and create a new one to get around the CLA?

**Pull request merged**
