### PR TITLE
Created rocks.yaml

### PR DESCRIPTION
**Pull request by kolobok01**
/kind feature

### CODE REVIEW

**Comment by tpepper** [comment]
As Guin just mentioned you may have a mismatch in your git config versus when you signed the CLA: https://github.com/kubernetes-sigs/contributor-playground/blob/master/exercises/cla-vs-git-author.md

**Comment by guineveresaenger** [comment]
/close 
for cleanup - feel free to `/reopen` if you like!
For further CLA trouble, email the helpdesk: helpdesk@rt.linuxfoundation.org

**Pull request closed without merging**
