### PR TITLE
add WuHan as the next KubeCon candidate city

### PR DESCRIPTION
**Pull request by hellmage**

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
agreed! :tada:
BTW, you need to sign your CLA before we can merge this PR :)
/lgtm
/approve

**Comment by carlisia** [comment]
Hey @hellmage did you get an email confirmation that your CLA was signed and accepted?

**Comment by hellmage** [comment]
I just found that I've committed the code with a wrong email. I changed the commit email and pushed with "--force". The email should be OK. Cheking CLA.

**Comment by hellmage** [comment]
@carlisia Seems /check-cla not working. Could you take a look? Thanks

**Pull request closed without merging**
