### PR TITLE
feat: add duckhue01.md

### PR DESCRIPTION
**Pull request by duckhue01**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add vietnam/DK.md
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by duckhue01** [comment]
@jberkus @MadhavJivrajani could pls review my pr when you have time?

**Comment by shu-mutou** [comment]
Please do not create a new directory to practice creating a PR.
Please practice creating PRs in the `/remote/learners/` directory, if so I can review it.

**Comment by duckhue01** [comment]
@shu-mutou Please help me check again

**Comment by shu-mutou** [comment]
Enjoy your contribution!!
/woof

**Pull request merged**
