### PR TITLE
Add foo md kuji2(retry)

### PR DESCRIPTION
**Pull request by kujiraitakahiro**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by atoato88** [comment]
/lgtm
/approve
Perfect! :smile: 
Welcome to k8s community!
And it's great action tried multiple times.

**Comment by atoato88** [comment]
Just one comment.

It's better to set target `/kind` by writting as follows:
```
/kind documentation
```
not 
```
> Uncomment only one /kind <> line, hit enter to put that in a new line, and remove leading whitespaces from that line:
> /kind documentation
```
- remove first comment: `> Uncomment only one /kind <> line, hit enter to put that in a new line, and remove leading whitespaces from that line:`
- without leading `> ` on line of `/kind xxxxx`.

**Comment by s-kawamura-w664** [comment]
Congratulations on your first PR.

**Comment by kujiraitakahiro** [comment]
I see writing of "/king".
Thanx!!

**Pull request merged**
