### PR TITLE
added walt.md to remote/learners folder

### PR DESCRIPTION
**Pull request by waltribeiro**
**What type of PR is this?**

>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
add `walt.md` file

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:
None

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by waltribeiro** [comment]
@shu-mutou could I get a review?

**Comment by ziyi-xie** [comment]
Thanks! Welcome to the K8s community!
/lgtm
/approve

/meow

**Comment by waltribeiro** [comment]
> Thanks! Welcome to the K8s community! /lgtm /approve
> 
> /meow

Thanks so much! 🙇🏻 💻

**Pull request merged**
