### PR TITLE
update link to code-of-conduct in japan attendee prerequisites

### PR DESCRIPTION
**Pull request by ymgyt**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

update not found link in japan/attendee-prerequisties

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

None

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Review by Okabe-Junya — COMMENTED** [review]
めちゃ助かります！

/lgtm
/approve

**Comment by nasa9084** [comment]
かぶった

**Comment by shu-mutou** [comment]
/lgtm
/approve
Welcome to k8s community!! :tada:

**Pull request merged**
