### PR TITLE
add alessandrofazio.md to remote/learners folder

### PR DESCRIPTION
**Pull request by AlessandroFazio**
add alessandrofazio.md to remote/learners folder

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by AlessandroFazio** [comment]
@shu-mutou could I get a review? Thanks.

**Comment by ziyi-xie** [comment]
Thanks! Welcome to the K8s community!
/lgtm
/approve

/meow

**Comment by AlessandroFazio** [comment]
Thank you so much!❤️

**Pull request merged**
