### PR TITLE
adding mihneaspirescu to repo

### PR DESCRIPTION
**Pull request by mihneaspirescu**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
* Adding mihneaspirescu to repo.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by shu-mutou** [comment]
please do not delete LEARNERS file

**Comment by mihneaspirescu** [comment]
Thanks @shu-mutou. Having a folder named `learners` and a file `LEARNERS` doesn't play well in certain macOS dev environments given that the default Apple File System (APFS) config is case-insensitive. I'll close the PR as it was open to sign the CLA. Thanks!

**Comment by shu-mutou** [comment]
Thanks for reporting the problem in MacOS! I addressed this issue on #1056.

**Pull request closed without merging**
