### PR TITLE
update vikramcse workdir

### PR DESCRIPTION
**Pull request by vikramcse**
**What type of PR is this?**
> /kind documentation

**What this PR does / why we need it**:
Update to vikramcse workdir

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:
None

**Does this PR introduce a user-facing change?**:
```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
None
```

### CODE REVIEW

**Comment by palnabarun** [comment]
Hi 👋🏽, can you please let us know your email ID for us to email you the coupon code for swags?

**Comment by vikramcse** [comment]
Thank You @palnabarun 
my email id is: vikramcse.10@gmail.com

**Pull request merged**
