### PR TITLE
Create karthik.md

### PR DESCRIPTION
**Pull request by karthikv81**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by shu-mutou** [comment]
I recommend that you do this in the `/remote/` directory, as this directory is not so active.

**Comment by shu-mutou** [comment]
I recommend that you do this in the `/remote/` directory, if so I can review it.

**Comment by karthikv81** [comment]
Moved to /remote folder as per review comment

**Comment by shu-mutou** [comment]
Please create your file into remote/learners/ directory.
Your second commit seems to remove your file. Thanks!

**Comment by shu-mutou** [comment]
/lgtm
/approve
Perfect!!
Welcome to K8s community 🎉

**Comment by shu-mutou** [comment]
Enjoy your contribution!!
/honk

**Pull request merged**
