### PR TITLE
add yasuraok.md

### PR DESCRIPTION
**Pull request by yasuraok**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add yasuraok.md for practice in ossj-2021 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Nothing

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig node

### CODE REVIEW

**Comment by atoato88** [comment]
oh! super fast PR creating! :smile: 
It's looks good.
/approve

**Comment by atoato88** [comment]
And LGTM
/lgtm

**Comment by YuikoTakada** [comment]
Thank you for your PR!
/lgtm

**Comment by atoato88** [comment]
"linux-foundation-easycla" bot says some errors, but it's not a problem.
because CLA is migrationg to this easycla, but it has not been complete yet.
For comple today hands-on, we need the `cncf-cla: yes` label only.( and it's labeld to this PR already)

**Comment by yasuraok** [comment]
(This is already merged but I want to test some commands)

/meow

**Pull request merged**
