### PR TITLE
Add hourglasshoro.md in cndo-2021

### PR DESCRIPTION
**Pull request by hourglasshoro**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add hourglasshoro.md for cndo-2021 demo.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by YuikoTakada** [comment]
/lgtm
/approve

thank you for your PR :)

**Comment by shu-mutou** [comment]
/lgtm
Perfect!! Thank you for your contribution!

**Pull request merged**
