### PR TITLE
Hello Beijing

### PR DESCRIPTION
**Pull request by weibaohui**
Hello Beijing

### CODE REVIEW

**Comment by weibaohui** [comment]
> Hi @weibaohui! Are you running a workshop in Beijing? Awesome! I'm happy to approve if you tell me the purpose of the Beijing folder. 😃

Hi,I want to make this folder a great place to share ideas,  for peoples who loves Kubernetes in Beijing.
thanks!

**Comment by weibaohui** [comment]
> Ah! Apologies for the delay.
> 
> So this repo's purpose is mainly to give (mostly new) contributors a place to test out how to interact with the Kubernetes bot automation on pull requests.
> 
> If you want to run a new contributor workshop or presentation (or just practice with colleagues), this is the repo you should use. If you want to have discussion and ideas around Kubernetes, please check out our [community page](http://kubernetes.io/community/) - we know that there are some very China-specific pain points and are actiuvely looking for ways to work with that.
> 
> In order to run your own workshop, you will want to consider adding an OWNERS file to your subfolder. You can find resources and some examples in the `presentations` and `exercises` folders, and of course sig-contributor-experience is happy to help!

Thanks for guiding me, now I have added the OWNERS file.
This is a good exercise opportunity！

**Comment by guineveresaenger** [comment]
/approve

Good luck with your exercises! 🎉

**Comment by weibaohui** [comment]
@guineveresaenger 
thank you ,this is awesome !

**Pull request merged**
