### PR TITLE
Added tuibeovince.md file

### PR DESCRIPTION
**Pull request by tuibeovince**
**What type of PR is this?**
 /kind documentation

**What this PR does / why we need it**:
First commit PR

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
```

### CODE REVIEW

**Comment by shu-mutou** [comment]
Welcome to k8s community!! :tada: 

For the second half of the PR comment, please write like follow while checking the `Preview`:
image

**Comment by shu-mutou** [comment]
You can refer to the following and add a joke comment.

https://prow.k8s.io/command-help?repo=kubernetes-sigs%2Fcontributor-playground

**Comment by tuibeovince** [comment]
> Welcome to k8s community!! 🎉
> 
> For the second half of the PR comment, please write like follow while checking the `Preview`: image

I applied the fixes to make it look more similar to the comment.

**Comment by shu-mutou** [comment]
/lgtm
/approve
Thanks!

**Pull request merged**
