### PR TITLE
Update the Barcelona contributor page as first PR

### PR DESCRIPTION
**Pull request by gangchen03**
Test Kubernetes PR process by adding to this file.
You can review the updated filed at:
https://github.com/gangchen03/contributor-playground/blob/master/barcelona/OWNERS

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
To validate the contribution process as new contributor

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Thank you!

**Does this PR introduce a user-facing change?**:
No

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by gangchen03** [comment]
> * signed a CLA

Signed CLA with commit email `gangchen.dev@gmail.com`. Please verify.

**Comment by idealhack** [comment]
> The following users are mentioned in OWNERS file(s) but are not members of the kubernetes-sigs org.

Hmm... we often add new contributors into the OWNERS file in this repo to let them practice, we might want to opt-out for this repo

**Comment by idealhack** [comment]
looks like it's fixed, thanks @nikhita!

/unassign
/assign @jeefy

**Comment by ameukam** [comment]
Hi @gangchen03, Thank you for attending the contributor summit!!
Sorry to the late response on this PR but it will be closed.

/close

**Pull request closed without merging**
