### PR TITLE
kcdblr: Add rahulgrover99 workdir

### PR DESCRIPTION
**Pull request by rahulgrover99**
Signed-off-by: Rahul Grover <rahulgrover99@gmail.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Update rahulgrover99's workdir snapshot

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:
None

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
@rahulgrover99 Congratulations on successfully getting your PR merged to kubernetes! :tada: 

Can you please let us know your email ID for us to email you the coupon code for swags?

You can either post your email as a comment here (on this PR) or DM me on the [Kubernetes](https://slack.k8s.io/) slack (I'm `@nikhita` on slack).

**Comment by rahulgrover99** [comment]
@nikhita Thank you so much for the amazing workshop once again! My email id is `rahulgrover99@gmail.com` 😄

**Pull request merged**
