### PR TITLE
Add eppppi.md for cndt-2022 demo

### PR DESCRIPTION
**Pull request by eppppi**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add eppppi.md for cndt-2022 demo

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig testing

### CODE REVIEW

**Comment by atoato88** [comment]
Thank you for creating PR!
Please see this documents for signing CLA.
https://github.com/kubernetes-sigs/contributor-playground/blob/master/japan/assets/attendee-prerequisites.md#%E3%82%B5%E3%82%A4%E3%83%B3%E3%82%A2%E3%83%83%E3%83%97%E4%BD%9C%E6%A5%AD

**Comment by oomichi** [comment]
Thanks for your first contribution! :cat:

/approve

**Pull request merged**
