### PR TITLE
Add y_nishimura.md

### PR DESCRIPTION
**Pull request by hao03**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Add y_nishimura.md for training.
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
/sig testing
```

### CODE REVIEW

**Comment by khrd** [comment]
#431 👀

**Comment by hao03** [comment]
/lgtm
LGTM

**Pull request merged**
