### PR TITLE
The previous link should point to a multilingual directory now

### PR DESCRIPTION
**Pull request by blueabysm**
**What type of PR is this?**
> /kind bug

**What this PR does / why we need it**:
The original link https://git.k8s.io/community/contributors/guide/contributor-cheatsheet.md referred by `Contributor Cheat Sheet` is no longer available (404). It should point to a multilingual directory now.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by blueabysm** [comment]
It's my first contribution, thanks for your reviewing 😁

**Comment by guineveresaenger** [comment]
/approve
/lgtm

Thank you for your pull request helping us keep things up to date! @blueabysm !  🎉

**Pull request merged**
