### PR TITLE
Add hello from table X

### PR DESCRIPTION
**Pull request by girikuncoro**
/sig contributor-experience
/kind documentation

### CODE REVIEW

**Comment by dwmkerr** [comment]
Baik!

**Comment by dwmkerr** [comment]
@girikuncoro can you add yourself to the approvers list in this PR?

**Comment by girikuncoro** [comment]
@dwmkerr done, can you review again?

**Comment by niyue** [comment]
one more approver, great /approve

**Comment by dwmkerr** [comment]
@niyue can you approve?

**Pull request merged**
