### PR TITLE
Added my workdir

### PR DESCRIPTION
**Pull request by vedant-kakde**
What type of PR is this?
/kind documentation

What this PR does / why we need it:
Update Vedant Kakde workdir snapshot

Which issue(s) this PR fixes:
None

Special notes for your reviewer:
None

```docs
None
```

### CODE REVIEW

**Comment by RinkiyaKeDad** [comment]
Hi 👋🏽, can you please let us know your email ID for us to email you the coupon code for swags?

**Comment by vedant-kakde** [comment]
@RinkiyaKeDad  vedantkakde651@gmail.com . Thank you 😄.

**Comment by RinkiyaKeDad** [comment]
Sent :)

**Comment by vedant-kakde** [comment]
ohh man  this image 🤣🤣

**Pull request merged**
