### PR TITLE
Declaring that K8s is awesome

### PR DESCRIPTION
**Pull request by chrishna1**
/kind documentation

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by palnabarun** [comment]
Hi 👋🏽, thank you for your pull request! 🎉 

Can you please send me an email at `404@naba.run`? We need your email ID for sending the swag code.

We look forward to seeing you in the community! 🙂

**Comment by chrishna1** [comment]
Sure. 
Thanks for the introductory hands-on session.

**Pull request merged**
