### PR TITLE
add mochizuki875.md

### PR DESCRIPTION
**Pull request by mochizuki875**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Add hands-on doc cndt-2020/workdir/mochizuki875.md.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by s-ito-ts** [comment]
/meow
/lgtm
/approve
Thanks!!

**Comment by mochizuki875** [comment]
@s-ito-ts Thank you for your approve:)

**Comment by mochizuki875** [comment]
check-cla

**Pull request merged**
