### PR TITLE
Add eiiches.md for CNDO-2021 training

### PR DESCRIPTION
**Pull request by eiiches**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
Add eiiches.md for CNDO-2021 training

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig testing

### CODE REVIEW

**Comment by YuikoTakada** [comment]
/lgtm
/approve

thank you for your PR : ) Looks good to me!

**Comment by eiiches** [comment]
@YuikoTakada Thanks!

**Comment by s-ito-ts** [comment]
Thank you for your contribution!

**Pull request merged**
