### PR TITLE
add soichiro-ueda.md for hands-on

### PR DESCRIPTION
**Pull request by Saza-ku**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR adds soichiro-ueda.md. This is greeting from Soichiro Ueda.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by atoato88** [comment]
Thank you for creating PR!
Please see this documents for signing CLA.
https://github.com/kubernetes-sigs/contributor-playground/blob/master/japan/assets/attendee-prerequisites.md#%E3%82%B5%E3%82%A4%E3%83%B3%E3%82%A2%E3%83%83%E3%83%97%E4%BD%9C%E6%A5%AD

**Comment by Saza-ku** [comment]
Hi, @atoato88 ! I signed CLA. Thanks!

**Comment by atoato88** [comment]
Welcome to k8s community!!

/lgtm
/approve

/bark

**Pull request merged**
