### PR TITLE
Add kaitok.md

### PR DESCRIPTION
**Pull request by kaitokimuraofficial**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind documentation

**What this PR does / why we need it**:
Add `kaitok.md`

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig node
/sig testing

### CODE REVIEW

**Comment by ziyi-xie** [comment]
Thanks! Welcome to the K8s community!
/lgtm
/approve

/meow

**Comment by atoato88** [comment]
/lgtm
/approve

Great!
It's good time to try some joke commands here!
Try it! :smile: 
https://prow.k8s.io/command-help

**Pull request merged**
