### PR TITLE
Add rung-test.md to cndt-2021 (training)

### PR DESCRIPTION
**Pull request by rung**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add rung-test.md to cndt-2021

**Which issue(s) this PR fixes**:
Fixes # Nothing :)

**Special notes for your reviewer**:
None

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig testing

### CODE REVIEW

**Comment by shu-mutou** [comment]
/lgtm
/approve
Perfect!! Welcome to the kubernetes community! 🎉

**Comment by rung** [comment]
@shu-mutou Thank you so much!

**Pull request merged**
