### PR TITLE
add riita10069.md into cndt-2021

### PR DESCRIPTION
**Pull request by riita10069**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
add riita10069.md into cndt-2021 for hands-on

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig testing

### CODE REVIEW

**Comment by atoato88** [comment]
It looks good!! :smile:

**Comment by shu-mutou** [comment]
/lgtm
Perfect!! Thanks!

**Comment by riita10069** [comment]
@shu-mutou @atoato88 @YuikoTakada 
Thanks for your review!!

**Pull request merged**
