### PR TITLE
Add folder for cndt-2020

### PR DESCRIPTION
**Pull request by atoato88**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

We will hold Kubernetes upstream training In a public event CloudNative Days Tokyo 2020.
This PR adds work place folder for the event and some assets for training, and also OWNERS file.

**Which issue(s) this PR fixes**:

NONE

**Special notes for your reviewer**:

NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

NONE

### CODE REVIEW

**Comment by atoato88** [comment]
/assign @parispittman

Could you review this?

**Comment by shu-mutou** [comment]
Folders for events in Japan become increase.
How about create `japan` folder and gather them into it?

**Comment by atoato88** [comment]
@shu-mutou 
It's OK to me, but I think it should be done by other PR.
This PR is for next training on CloudNative Days Tokyo 2020 in Japan.

WDYT?

**Comment by shu-mutou** [comment]
/lgtm
Thanks!

**Pull request merged**
