### PR TITLE
add Ali90922.md to remote/learners folder

### PR DESCRIPTION
**Pull request by Ali90922**
What type of PR is this?
/kind documentation

What this PR does / why we need it:
Add `Ali90922.md` to the `remote/learners` folder for practicing PR submission.

Which issue(s) this PR fixes:
Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:
NONE

Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by Ali90922** [comment]
Hi @nasa9084,

Thank you for reviewing the pull request! I noticed that the /lgtm command might have been misspelled as /lgm, which is preventing the merge. Could you kindly update it to /lgtm when you get a chance? Thanks again for your help!

**Comment by shu-mutou** [comment]
/lgtm
Welcome to K8s community 🎉
Enjoy your contribution!!
/meow

**Pull request merged**
