### PR TITLE
Adds a new approver

### PR DESCRIPTION
**Pull request by smourapina**
I will be an approver after this!

### CODE REVIEW

**Comment by tpepper** [comment]
It looks like we didn't not back up far enough...

Try:

1) git reset --hard bd0ff6f3936a9cbca35d570e00e3eb21e5c1f978
2) re-do your file edits
3) commit
4) git push --force

**Comment by smourapina** [comment]
Thank you so much @tpepper!

**Comment by tpepper** [comment]
/lgtm

🎉

**Comment by idealhack** [comment]
you should try this in `shanghai` directory :P

**Comment by jberkus** [comment]
Since she can't actually be an approver in the root directory, closing this.

Nice test of the system, though!

/close

**Pull request closed without merging**
