### PR TITLE
Create priyamsamanta

### PR DESCRIPTION
**Pull request by psamanta12**
> /kind documentation

**What this PR does / why we need it**:
update workdir

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:
None
**Does this PR introduce a user-facing change?**:
None
```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
None
```docs

```

### CODE REVIEW

**Comment by psamanta12** [comment]
Thanks for approving

**Comment by nikhita** [comment]
@psamanta12 Congratulations on successfully getting your PR merged to kubernetes! :tada: 

Can you please let us know your email ID for us to email you the coupon code for swags?

You can either post your email as a comment here (on this PR) or DM me on the [Kubernetes](https://slack.k8s.io/) slack (I'm `@nikhita` on slack).

**Comment by psamanta12** [comment]
@nikhita My email id is - priyam7699@gmail.com

**Pull request merged**
