### PR TITLE
add levi106.md for ood-2022

### PR DESCRIPTION
**Pull request by levi106**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ziyi-xie** [comment]
Thanks~ Welcome to the community~
/lgtm

**Comment by oomichi** [comment]
Thanks!

/approve

**Comment by levi106** [comment]
@ziyi-xie , @oomichi 
Thanks for your review.

**Pull request merged**
