### PR TITLE
Add remote directory

### PR DESCRIPTION
**Pull request by parrasajad**
Remote directory is for all those who are learning through youtube videos and blogs

### CODE REVIEW

**Comment by idealhack** [comment]
I like this idea.

/lgtm
/lifecycle frozen

**Comment by nikhita** [comment]
/remove-lifecycle frozen

cc @mrbobbytables @castrojo

**Comment by nikhita** [comment]
Created https://github.com/kubernetes-sigs/contributor-playground/pull/519 to update OWNERS

**Pull request merged**
