### PR TITLE
Create aniket.md

### PR DESCRIPTION
**Pull request by Aniket762**
**What type of PR is this?**
 /kind documentation

> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Adding an entry for Aniket

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by CIPHERTron** [comment]
Congratulations on your first PR to Kubernetes 🎉 
/woof

**Comment by MadhavJivrajani** [comment]
/lgtm
/approve
Welcome!

**Comment by MadhavJivrajani** [comment]
@Aniket762 thank you for submitting the PR!
Since you were one of the few to successfully submit a PR, we'd like to send some swag your way! Please reach out to me on the HackIllinois slack or the K8s slack (`@madhav`) so that I can relay the necessary info to you :)

**Pull request merged**
