### PR TITLE
Update location of slide for Japan events

### PR DESCRIPTION
**Pull request by atoato88**
This PR updates a location of slide used on Japan events.

As of now, Japan's event mentors registered single pdf file to each training folder.
These files are pretty big file size and almost same contents with each events' one.

It's good to change slide location to single latest slide from each event folders
and this make this repository small.
By this commit, we can clone more speedy by `git clone`.

### CODE REVIEW

**Comment by atoato88** [comment]
Beside this, should I change about `docs/attendee-prerequisites.md` on each folder by same policy?

**Comment by atoato88** [comment]
Thank you to quick response, I'll update code-set.

**Comment by shu-mutou** [comment]
Also, it's good to move `hands_on.md` under some directories, I think. 😉

**Comment by atoato88** [comment]
I've updated PR.
Could you review again?

**Comment by shu-mutou** [comment]
/lgtm
Great job!

**Pull request merged**
