### PR TITLE
First commit to update dbhaskaran workspace

### PR DESCRIPTION
**Pull request by dbhaskaran**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
None 
**Which issue(s) this PR fixes**:
None
Fixes #

**Special notes for your reviewer**:
Thank you for the workshop
**Does this PR introduce a user-facing change?**:
No
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
None

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
should get merged soon @dbhaskaran :)

**Comment by dbhaskaran** [comment]
Ah, thank you :)

**Comment by RinkiyaKeDad** [comment]
Hi 👋🏽, can you please let us know your email ID for us to email you the coupon code for swags?

**Comment by RinkiyaKeDad** [comment]
Hey @dbhaskaran can you please provide us your email? If you're not comfortable posting it here you can instead DM me on the [k8s](https://slack.k8s.io/) slack (I'm `@arsh` there).

**Comment by dbhaskaran** [comment]
@RinkiyaKeDad Hi there, my email is deepak.ny007@gmail.com Thank you.

**Comment by RinkiyaKeDad** [comment]
Sent :)

**Pull request merged**
