### PR TITLE
Saul's first PR

### PR DESCRIPTION
**Pull request by Sarony11**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ziyi-xie** [comment]
Thank you for your PR!
I just noticed that no one seems to have commented on your PR yet, 
maybe I can help if you practice in [the remote folder](https://github.com/kubernetes-sigs/contributor-playground/tree/master/remote/learners)~

**Comment by Sarony11** [comment]
I hope I have done it right. Otherwise, please tell me :)

**Comment by ziyi-xie** [comment]
Thank you for the modification!
Since the folders are managed separately, is it possible to delete the [murcia/saul-first-pr.md](https://github.com/kubernetes-sigs/contributor-playground/pull/1109/files#diff-ec71e214ab95b045a2bde018b6db4886789214476f8e1ac65638fc55b4967089) file?

**Pull request closed without merging**
