### PR TITLE
Add hoshymo.md into cncj-202403 for demo

### PR DESCRIPTION
**Pull request by hoshymo**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind documentation

**What this PR does / why we need it**:
Add hoshymo.md into cncj-202403 for demo

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by mkimuram** [comment]
@hoshymo Thank you for creating this PR! It seems that CLA check hasn't been passed, yet. 
Could you check if you signed the CLA  and let me notify again if it is marked as pass?

**Comment by hoshymo** [comment]
@mkimuram CLA sign やってみましたいかがでしょう...?

**Pull request merged**
