### PR TITLE
Github user Shumakriss ready to sign CLA

### PR DESCRIPTION
**Pull request by Shumakriss**
Requesting CLA sign/approval

### CODE REVIEW

**Comment by ziyi-xie** [comment]
Thanks! I think the problem will be solved if you click the red button that says "NOT COVERED" 
Also this is a practice repository, so please follow the PR template if possible :)

**Comment by Shumakriss** [comment]
Thank you! I have gone through the authorization process (I received a PDF after signing) but it will not update as authorized so I've submitted a support request ticket. Apologies for not using the template, I wrongly assumed that it was not intended as practice and just carried-over from other repos. I will make sure to follow the template in the future!

**Comment by ziyi-xie** [comment]
No worries! Thanks! Welcome to the K8s community!
/lgtm
/approve

/meow

**Pull request merged**
