### PR TITLE
Add shinichi-abe-dev.md for ood-2022.demo

### PR DESCRIPTION
**Pull request by Shinichi-Abe-dev**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add shinichi-abe-dev.md

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig node

### CODE REVIEW

**Comment by ziyi-xie** [comment]
Thanks! Welcome to the community! 
/lgtm

**Comment by Shinichi-Abe-dev** [comment]
Please leave a review

**Pull request merged**
