### PR TITLE
Test PR.

### PR DESCRIPTION
**Pull request by s-kawamura-w664**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This is a PR test.

### CODE REVIEW

**Comment by shu-mutou** [comment]
I created new dir `/japan/adhoc/workdir/` for practicing anytime.
Please move your file `test.md` to `/japan/adhoc/workdir/s-kawamura-w664.md`. Thanks!

**Comment by atoato88** [comment]
@s-kawamura-w664 
Thank you to create first PR! :tada: 
File contents is good, but file location is root of Japan training, so it will a few noisy for other contributors.
Could you change file location to other place?
IMHO, `japan/adhoc/workdir/` is good place for that. it is created by #585 .

**Comment by s-kawamura-w664** [comment]
@shu-mutou @atoato88 
I moved japan/test.md to japan/adhoc/workdir/s-kawamura-w664.md.

**Comment by atoato88** [comment]
/lgtm
/approve
Good PR!!
Thank you to change file location.
It's perfect!!😄

**Pull request merged**
