### PR TITLE
Create hello-ram.md

### PR DESCRIPTION
**Pull request by empiricaldevops**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Saying hi!
**Does this PR introduce a user-facing change?**:
NONE
```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by palnabarun** [comment]
Hi 👋🏽, can you please let us know your email ID for us to email you the coupon code for swags?

**Comment by empiricaldevops** [comment]
Hi Nabarun,

Email id- ***@***.***

Thanks

**Comment by MadhavJivrajani** [comment]
@empiricaldevops I think email masking is on, maybe comment from the PR page?

**Comment by empiricaldevops** [comment]
@palnabarun @MadhavJivrajani Hi, my email id - ramakumarja@gmail.com. Thanks

**Pull request merged**
