### PR TITLE
Change to add Gavin as a reviewer

### PR DESCRIPTION
**Pull request by gavinmcnair**

### CODE REVIEW

**Comment by gavinmcnair** [comment]
CLA signed.

**Comment by gavinmcnair** [comment]
"I signed it"

**Comment by gavinmcnair** [comment]
"I signed it"

**Comment by tpepper** [comment]
Thank you for coming to the workshop!  We hope you found it valuable and look forward to seeing you active in our Kubernetes community!

If you want to practice git rebase & git push --force for the above we can merge it for you otherwise will close...

**Comment by tpepper** [comment]
/close

can re-open if rebased.

**Pull request closed without merging**
