### PR TITLE
feat: add hangzhou

### PR DESCRIPTION
**Pull request by shimron**

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Awesome! But seems like that you haven't signed your CLA :)

**Comment by xiangpengzhao** [comment]
cool! CLA is ok now
/lgtm
/approve

**Comment by xiangpengzhao** [comment]
Seems like we can only change things in subdir shanghai :)

**Comment by idealhack** [comment]
/close

Feel free to reopen if there're any events happen in Hangzhou in the future!

**Pull request closed without merging**
