### PR TITLE
add frankyang-code4fun as remote learner

### PR DESCRIPTION
**Pull request by frankyang-code4fun**
Going through contributor workshop videos, and following the instructions to try out my first kubernetes development workflow.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by shu-mutou** [comment]
LGTM
Welcome to k8s community!

@nikhita @palnabarun @mrbobbytables @cblecker
Could you add me into OWNERS file under `remote` as a approver ?

**Comment by mrbobbytables** [comment]
@shu-mutou Added you in PR #1019 :)

**Review by mrbobbytables — COMMENTED** [review]
/approve

**Comment by shu-mutou** [comment]
/lgtm
Welcome to k8s community!! :tada:

**Pull request merged**
