### PR TITLE
Updated jayesh.md

### PR DESCRIPTION
**Pull request by JayeshShukla**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1067 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```
NONE

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Comment by JayeshShukla** [comment]
@nikhita, what does tide/merge-method-squash, signify ?

**Comment by nikhita** [comment]
> @nikhita, what does tide/merge-method-squash, signify ?

When your PR will be merged, it will [squash](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits) your commits into a single commit.

I added that because Kubernetes prefers very clean commits. Unless there are very big changes per commit, we try to have it all in a single commit.

**Comment by JayeshShukla** [comment]
tqs @nikhita .

**Pull request merged**
