### PR TITLE
Add jnytnai0613-w664.md for cndt2022

### PR DESCRIPTION
**Pull request by jnytnai0613**
What type of PR is this?
/kind documentation

What this PR does / why we need it:
add jnytnai0613-w664.md for cndt-2022 handson

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

### CODE REVIEW

**Comment by oomichi** [comment]
The content itself seems good for me.
We just need to wait for CLA.

/approve

**Comment by shu-mutou** [comment]
Please see this documents for signing CLA.
https://github.com/kubernetes-sigs/contributor-playground/blob/master/japan/assets/attendee-prerequisites.md#%E3%82%B5%E3%82%A4%E3%83%B3%E3%82%A2%E3%83%83%E3%83%97%E4%BD%9C%E6%A5%AD

**Comment by shu-mutou** [comment]
Great! Welcome to k8s community!!

**Pull request merged**
