### PR TITLE
Create rahul.md

### PR DESCRIPTION
**Pull request by Rahul-D78**
**What type of PR is this?**
/kind documentation
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> 
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
just a document update .
**Which issue(s) this PR fixes**:

Fixes #
document creation
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
/woof
/lgtm
/approve

Yay!

**Comment by Rahul-D78** [comment]
oooooo! is it merged could not express my feelings 🔥🔥🔥🔥

**Comment by palnabarun** [comment]
Hi 👋🏽, can you please let us know your email ID for us to email you the coupon code for swags?

**Comment by Rahul-D78** [comment]
HI @palnabarun  my email is rahulparida933@gmail.com

**Comment by Rahul-D78** [comment]
***@***.***

**Pull request merged**
