### PR TITLE
add hoge_polar3130.md 

### PR DESCRIPTION
**Pull request by polar3130**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig node

### CODE REVIEW

**Comment by atoato88** [comment]
/lgtm
/approve

Awesome PR!!

**Comment by polar3130** [comment]
Thanks a lot @atoato88 !

**Pull request merged**
