### PR TITLE
added praduman.md

### PR DESCRIPTION
**Pull request by praduman8435**
**What type of PR is this?**

> /kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by shu-mutou** [comment]
I recommend that you do this in the `/remote/` directory, if so I can review it.

**Comment by praduman8435** [comment]
Hi! @shu-mutou, I have done this in remote directory

**Comment by shu-mutou** [comment]
/lgtm
/approve
Perfect! Welcome to K8s community 🎉

**Comment by shu-mutou** [comment]
Enjoy your contribution!!
/meow

**Pull request merged**
