### PR TITLE
add Akiyama.md into cncj-202403 for demo

### PR DESCRIPTION
**Pull request by YamasouA**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind documentation

**What this PR does / why we need it**:
add Akiyama.md into cncj-202403 for demo

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
NONE
**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ziyi-xie** [comment]
Thanks! Welcome to the K8s community!
/lgtm
/approve

/meow

**Comment by shu-mutou** [comment]
/lgtm
Welcome to K8s community! :tada:

**Pull request merged**
