### PR TITLE
opensource k8s

### PR DESCRIPTION
**Pull request by ggupthavitob**
What type of PR is this?
    /kind documentation
What this PR does / why we need it:
just like that @ggupthavitob want to enroll as a remote learner
Which issue(s) this PR fixes:
Fixes None
Special notes for your reviewer:
Just be a kind
Does this PR introduce a user-facing change?:
NONE
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
NONE
/cc @nikhita @palnabarun
/woof

### CODE REVIEW

**Comment by palnabarun** [comment]
Hi @ggupthavitob 👋🏽, can you please rename the file to <your username>.md?

**Comment by ggupthavitob** [comment]
> Hi @ggupthavitob 👋🏽, can you please rename the file to .md?

Changed @palnabarun

**Comment by palnabarun** [comment]
Can you squash the commits as well? And, then this should be ready to merge.

**Comment by palnabarun** [comment]
Thank you and welcome! :D

/lgtm
/approve
/honk

**Pull request merged**
