### PR TITLE
kcdblr: Add Prathamesh Shanbhag

### PR DESCRIPTION
**Pull request by Prathamesh-Shanbhag**
Signed-off-by: Prathamesh Shanbhag prathameshshanbhag074@gmail.com

What type of PR is this?
/kind documentation

What this PR does / why we need it:
Update Prathameshshanbhag's snapshot

Which issue(s) this PR fixes:
None

Special notes for your reviewer:
None
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by Prathamesh-Shanbhag** [comment]
Hey, I haven't received the mail from the team yet! Waiting for it!

**Comment by MadhavJivrajani** [comment]
Hey, this PR unfortunately didn't end up in the top 30 :/ 
Next time! 🤞🏻

**Pull request merged**
