### PR TITLE
Add kos31de.md

### PR DESCRIPTION
**Pull request by kos31de**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind documentation

**What this PR does / why we need it**:

Because of contribution test.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by atoato88** [comment]
/lgtm
/approve

Perfect!!
Welcome to k8s contribution!! :tada:

**Comment by kos31de** [comment]
@atoato88 

Thanks!:smile:

**Comment by atoato88** [comment]
@kos31de 
BTW, where do you know this repository and adhoc folder?
Did you attend some k8s upstream training?
If you don't mind, please let me know.

**Comment by kos31de** [comment]
@atoato88 
While browsing Github, I happened to find this repository.
I had never heard of CLA before.
I wanted to try it out, so I configured it and created a PR based on [past PR](https://github.com/kubernetes-sigs/contributor-playground/pull/584).

**Comment by atoato88** [comment]
@kos31de 
It's so great! 😄 
Thank you for quick response.

**Pull request merged**
