### PR TITLE
test: my first pr

### PR DESCRIPTION
**Pull request by blue86321**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ziyi-xie** [comment]
Thank you for your contribution!
I think you can add your own files to [the remote folder](https://github.com/kubernetes-sigs/contributor-playground/tree/master/remote/learners) like https://github.com/kubernetes-sigs/contributor-playground/pull/1094 instead of revising the current README file if you want to practice~

**Comment by blue86321** [comment]
> Thank you for your contribution! I think you can add your own files to [the remote folder](https://github.com/kubernetes-sigs/contributor-playground/tree/master/remote/learners) like #1094 instead of revising the current README file if you want to practice~

Got it. I've edited the commit.

**Comment by ziyi-xie** [comment]
Thanks! Welcome to the k8s community~
/lgtm
/approve

And I noticed that your title and commit message is "test: my first pr", I think it might be even more perfect if you add more details (e.g. add blue86321 to remote/learners/LEARNERS file).

**Comment by blue86321** [comment]
> Thanks! Welcome to the k8s community~ /lgtm /approve
> 
> And I noticed that your title and commit message is "test: my first pr", I think it might be even more perfect if you add more details (e.g. add blue86321 to remote/learners/LEARNERS file).

Oh. That makes sense. Thank you for your advice, but the PR is merged I cannot edit the commit message anyway. 😢 But I'll keep in mind!

**Pull request merged**
