### PR TITLE
learning open-source

### PR DESCRIPTION
**Pull request by trishu99**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
learning open-source and K8S

**Which issue(s) this PR fixes**:
None
Fixes #

**Special notes for your reviewer**:
Please be Kind
**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by RinkiyaKeDad** [comment]
Hey @trishu99, you'll have to sign the CLA before we can merge this. You can refer to the workshop video where we showed it if you're confused about it. Please comment here if you still face any issues signing it 🙂

**Comment by trishu99** [comment]
Actually I have signed CLA before only, but not added that email, now added the email also... Hence, its now reflecting CLA signed. Thanks !!

**Comment by RinkiyaKeDad** [comment]
/lgtm
/approve
/woof
Welcome!

**Pull request merged**
