### PR TITLE
This my greeting contribution

### PR DESCRIPTION
**Pull request by amomsi**
This PR is just a part of the contribution workshop.

### CODE REVIEW

**Comment by amomsi** [comment]
I signed it

**Comment by shu-mutou** [comment]
/ lgtm
/approve
welcome to kubernetes community!!

**Comment by amomsi** [comment]
@shu-mutou thank you :)

**Comment by atoato88** [comment]
@amomsi 
Already this PR is merged, This was a perfect first PR by you!
Welcome.

**Pull request merged**
