### PR TITLE
Add foo.md

### PR DESCRIPTION
**Pull request by watany-dev**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind documentation

**What this PR does / why we need it**:
Adding Document for CNDT2022 Upstream Training

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by atoato88** [comment]
Thank you for creating PR!
Please see this documents for signing CLA.
https://github.com/kubernetes-sigs/contributor-playground/blob/master/japan/assets/attendee-prerequisites.md#%E3%82%B5%E3%82%A4%E3%83%B3%E3%82%A2%E3%83%83%E3%83%97%E4%BD%9C%E6%A5%AD

**Comment by oomichi** [comment]
Could you create `watany-dev.md` file instead of `foo` file to explain who was created cleary?

**Comment by oomichi** [comment]
humm, OK.
Many people already love this :-)

/lgtm

**Pull request merged**
