### PR TITLE
Add yuto-kimura-g.md into cndw-2024

### PR DESCRIPTION
**Pull request by yuto-kimura-g**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind documentation

**What this PR does / why we need it**:
Hands on: Add yuto-kimura-g.md into cndw-2024

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by mkimuram** [comment]
@yuto-kimura-g  Thank you for your first PR. Please sign the CLA to proceed.

**Comment by shu-mutou** [comment]
/lgtm
/approve
Welcome to K8s community!! :tada:

**Comment by shu-mutou** [comment]
Enjoy your contribution!!
/joke

**Pull request merged**
