### PR TITLE
added file.

### PR DESCRIPTION
**Pull request by snehaa1989**
What type of PR is this?
/kind documentation

What this PR does / why we need it:
Update sneha_k workdir

Which issue(s) this PR fixes:
None

Special notes for your reviewer:
None

### CODE REVIEW

**Comment by nikhita** [comment]
@snehaa1989 Congratulations on successfully getting your PR merged to kubernetes! :tada: 

Can you please let us know your email ID for us to email you the coupon code for swags?

You can either post your email as a comment here (on this PR) or DM me on the [Kubernetes](https://slack.k8s.io/) slack (I'm `@nikhita` on slack).

**Comment by snehaa1989** [comment]
snehasai01@gmail.com

**Pull request merged**
