### PR TITLE
First commit while attending "Contributing to Kubernetes 101" workshop.

### PR DESCRIPTION
**Pull request by ashwani99**

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

/woof

**Comment by palnabarun** [comment]
Hi 👋🏽, thank you for your pull request! 🎉 

Can you please send me an email at `404@naba.run`? We need your email ID for sending the swag code.

We look forward to seeing you in the community! 🙂

**Comment by ashwani99** [comment]
@palnabarun done

**Pull request merged**
