### PR TITLE
feat: add davidnuneslima.md

### PR DESCRIPTION
**Pull request by davidnuneslima**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
add davidnuneslima.md to brazil folder for practicing PR submission.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by shu-mutou** [comment]
Do not create a new directory to practice creating a PR.
Please practice creating a PR in the `remote` directory; the active reviewers are there.

**Comment by davidnuneslima** [comment]
> Do not create a new directory to practice creating a PR. Please practice creating a PR in the `/remote/learners/` directory; the active reviewers are there.

Hello @shu-mutou, thanks for the information. In this case, do you suggest closing this PR and opening a new one or do I keep it open and now I have knowledge of the remote/learner flow?

**Comment by davidnuneslima** [comment]
@jberkus @MadhavJivrajani can you support me if the PR is ready for approval or if I will have to open a new PR as instructed by the @shu-mutou ?

**Comment by shu-mutou** [comment]
@davidnuneslima All you have to do is add a commit that moves the file you're adding in this PR into `/remote/learners/` . You can also close this PR and create a new one. Either way is fine.

**Comment by shu-mutou** [comment]
/lgtm
/approve
Welcome to K8s community 🎉

**Comment by shu-mutou** [comment]
Enjoy your contribution!!
/meow

**Pull request merged**
