### PR TITLE
Update slide in japan folder latest

### PR DESCRIPTION
**Pull request by atoato88**
This PR updates slide in `japan/assets` to latest.
Japan members create this slide as independent from any events and will continue maintenance this as common asset for Japan trainings.

### CODE REVIEW

**Comment by atoato88** [comment]
/assign @shu-mutou @k-toyoda-pi 
I've assign to two of you, but approve from any approver is welcome. :smile:

**Comment by YuikoTakada** [comment]
@atoato88 Thank you for your PR! Looks good to me :)

**Comment by atoato88** [comment]
Please comment with slash-lgtm if OK.

**Pull request merged**
