### PR TITLE
Add README file to cncj-202403

### PR DESCRIPTION
**Pull request by atoato88**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR adds README.md file to cncj-202403 folder.
As of now, I'm cordinating facilitators, so I'll create other PR if all facilitators are fixed.

**Which issue(s) this PR fixes**:
NONE

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
NONE

### CODE REVIEW

**Comment by atoato88** [comment]
/assign @shu-mutou
Could you check about following points?:
- Is it correct the URL of event page
- The logo image of this event is sitill nothing? If so, should I remove the markup for the logo image?(currently, I commented out)

**Comment by atoato88** [comment]
/uncc @YuikoTakada @ziyi-xie 
I want to be reveiwed this PR by @shu-mutou, so I remove all reviewers.

**Comment by shu-mutou** [comment]
@atoato88 Thanks!! Anyway, we need README.md to setup our event. So I merge this.
Let's update this soon, if any updates are comming.

**Pull request merged**
