### PR TITLE
add foo_kzks.md  into cncj-202403 

### PR DESCRIPTION
**Pull request by kzks3001**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
> 
/kind documentation

**What this PR does / why we need it**:

add foo_kzks.md into cncj-202403 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```
None

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by shu-mutou** [comment]
/approve
Welcome to K8s community! :tada:

**Comment by kzks3001** [comment]
/honk
--

**Pull request merged**
