### PR TITLE
Add the photo on ood-2022

### PR DESCRIPTION
**Pull request by atoato88**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR adds the photo on Okinawa Open Days 2022.

**Which issue(s) this PR fixes**:
NONE

**Special notes for your reviewer**:
We got a lot of new contributors thanks to ood-2022.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
NONE

### CODE REVIEW

**Comment by atoato88** [comment]
/assign @oomichi 
/assign @ziyi-xie 
Could you review this?
And can you label "lgtm" if your result is OK.

**Comment by shu-mutou** [comment]
/gtm
/approve
thanks!!

**Comment by atoato88** [comment]
@shu-mutou

oh,, could you label by `/lgtm`?
Your command is `/gtm` instead it.

**Comment by shu-mutou** [comment]
(*ﾉω・*)ﾃﾍ

**Pull request merged**
