### PR TITLE
My first contibution to K8s  playground

### PR DESCRIPTION
**Pull request by Najeeb120**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR adds my name to the contributors' directory
**Which issue(s) this PR fixes**:
None

Fixes #

**Special notes for your reviewer**:
This is my first contribution to Kubernetes which is required to sign CLA.

**Does this PR introduce a user-facing change?**:

```release-note
No
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by Najeeb120** [comment]
@MadhavJivrajani  @RinkiyaKeDad  Could you please review this PR when you have a moment ?

**Comment by ziyi-xie** [comment]
Sorry I didn't mention before, I noticed that your title and commit message is "My first contibution to K8s playground", I think it might be even more perfect if you add more details for both of them(e.g. add remote/learners/Najeeb.md).

**Comment by shu-mutou** [comment]
/lgtm
/approve
Welcome to K8s community 🎉

**Pull request merged**
