### PR TITLE
add ziyi.md to remote/learners folder

### PR DESCRIPTION
**Pull request by ziyi-xie**
**What type of PR is this?**

 /kind documentation

**What this PR does / why we need it**:
add ziyi.md to remote/learners folder for practicing PR submission.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by shu-mutou** [comment]
/lgtm
/approve
Perfect!!
Welcome to Kubernetes community!!! :tada:

**Comment by MichaelRobotics** [comment]
What type of PR is this?

/kind documentation

What this PR does / why we need it:
add ziyi.md to remote/learners folder for practicing PR submission.

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

NONE
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

**Comment by Obasoro** [comment]
/kind documentation

What this PR does / why we need it:
for CLA signing

**Pull request merged**
