### PR TITLE
Add p0r7m.md

### PR DESCRIPTION
**Pull request by p0r7m**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
> 
/kind documentation

**What this PR does / why we need it**:

Contribution guidelines check

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```

```

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Hello @p0r7m , good day! May I know why this PR was submitted today?

**Comment by p0r7m** [comment]
> Hello @p0r7m , good day! May I know why this PR was submitted today?

Was going through the youtube playlist recently. Raised this PR to get an understanding of Kubernetes project's review and pull request processes before moving on to make an actual contribution.

**Pull request merged**
