### PR TITLE
Add myself to Seattle OWNERS

### PR DESCRIPTION
**Pull request by plaurin84**
Because I can do so.

### CODE REVIEW

**Comment by tpepper** [comment]
As Guin just mentioned you may have a mismatch in your git config versus when you signed the CLA: https://github.com/kubernetes-sigs/contributor-playground/blob/master/exercises/cla-vs-git-author.md

**Comment by plaurin84** [comment]
Yep I just realised that.
It worked first, then I sent another patch using signature. Which made it fail.

**Comment by plaurin84** [comment]
@tpepper cool that works, thx :1st_place_medal:

**Pull request closed without merging**
