### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by avinashnraj**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind documentation

**What this PR does / why we need it**:
adding avinashnraj.md to remote/learners folder for practicing PR submission.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by avinashnraj** [comment]
> **What type of PR is this?**
> 
> > Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
> > /kind documentation
> 
> **What this PR does / why we need it**:
adding avinashnraj.md to remote/learners folder for practicing PR submission.
> 
> **Which issue(s) this PR fixes**:
> 
> Fixes #
> 
> **Special notes for your reviewer**:
> 
> **Does this PR introduce a user-facing change?**:
> 
> ```
> 
> ```
> 
> **Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
> 
> ```
> 
> ```

**Comment by shu-mutou** [comment]
/lgtm
/approve
Welcome to K8s community 🎉

**Comment by shu-mutou** [comment]
Enjoy your contribution!!
/woof

**Comment by avinashnraj** [comment]
> Enjoy your contribution!! /woof

Thank you!

**Pull request merged**
