### PR TITLE
add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by hlb**
add CONTRIBUTING.md in barcelona/

### CODE REVIEW

**Comment by hlb** [comment]
I signed it

**Comment by tpepper** [comment]
/close

Nice attempt to seed some PRs during the workshop, but for future workshops and readers of the repo we should now keep the doc's existing content present.

Thank you for coming to the workshop!  We hope you found it valuable and look forward to seeing you active in our Kubernetes community!

**Pull request closed without merging**
