### PR TITLE
Add eto.md

### PR DESCRIPTION
**Pull request by etomitsue**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by shu-mutou** [comment]
Could you remove the comment in `type of PR`?

**Comment by etomitsue** [comment]
i fix it.
prease this PR

**Comment by shu-mutou** [comment]
Please refix as follow. Thanks.
```
**What type of PR is this?**
/kind documentation
```

**Comment by etomitsue** [comment]
Thanks. I fix it.
How about this?

**Comment by shu-mutou** [comment]
/lgtm
/approve
Excellent!! thanks!

**Comment by etomitsue** [comment]
thanks for hands on.

**Pull request merged**
