### PR TITLE
add contribution process diagram in jpg and original yEd format

### PR DESCRIPTION
**Pull request by emschu**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Illustrating graphically the k8s contribution workflow process

**Which issue(s) this PR fixes**:
No related issue.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig contribex

### CODE REVIEW

**Comment by guineveresaenger** [comment]
yay for CLA! a couple comments:

- can you fix the typo in the bottom box to read "kubernetes"?
- the bot that mergees your PR is called `k8s-ci-robot`, I think it will be clearer if you use its actual name.

Thank you for your contribution!

**Comment by emschu** [comment]
@guineveresaenger Thank you for reviewing this. Your suggestions have been applied.

**Comment by guineveresaenger** [comment]
Thank you for fixing!

/lgtm
/approve

Next: embed this file in the README, perhaps?

**Pull request merged**
