### PR TITLE
add aditi as a remote learner in India

### PR DESCRIPTION
**Pull request by aditi1230mhjn**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Initial Commit.

**Which issue(s) this PR fixes**:

Fixes: None
**Special notes for your reviewer**:
Please add me as remote learner. I would try to learn and contribute to K8 Open Source.
**Does this PR introduce a user-facing change?**:

```
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```
None
```

/cc @palnabarun @nikhita
/this-is-fine

### CODE REVIEW

**Comment by palnabarun** [comment]
Hi @aditi1230mhjn 👋🏽, do you want to maybe make your commit message a bit more verbose?

Like, "add aditi as a remote learner in India"? :)

**Comment by aditi1230mhjn** [comment]
Surely, I could make it that way. Thanks for your advice.

**Comment by palnabarun** [comment]
@aditi1230mhjn -- Thanks for changing the title of the PR. Could also please change the commit message?

You can follow along these steps:
```
$ git commit --amend -m "add aditi as a remote learner in India"
$ git push origin patch-1 --force
```

(assuming that you have followed the PR workflow and named the remote of your fork as `origin`)

**Pull request closed without merging**
