### PR TITLE
india: avinash init

### PR DESCRIPTION
**Pull request by avinashupadhya99**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design

/kind documentation

> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Adds Avinash's introduction. Not too sure why you would need it haha

**Which issue(s) this PR fixes**:

null

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
N/A
```

### CODE REVIEW

**Comment by palnabarun** [comment]
Hi 👋🏽, can you please let us know your email ID for us to email you the coupon code for swags?

**Comment by avinashupadhya99** [comment]
Hi Nabarun, thank you for the swags and opportunity!
Here's my email - `avinashupadhya99@gmail.com`

**Pull request merged**
